### ISSUE TITLE
Improve JSON assertions in tests

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/exasol-rest-api#13]
As @jakobbraun suggested, we can use additional library for more readable JSON assertions in tests:  https://github.com/kinbiko/jsonassert

**Comment by AnastasiiaSergienko** [comment]
Additional improvements for tests: check if assertAll exists in some go library.

**Comment by pj-spoelders** [comment]
Closing this ticket. Has little relevancy today. 
If anyone disagrees feel free to open it again or create a new ticket.
