### ISSUE TITLE
Add support for certificate fingerprints

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-rest-api#27]
We should add support for certificate fingerprints. This could be implemented by using [exasol-driver-go](https://github.com/exasol/exasol-driver-go) which supports fingerprints since https://github.com/exasol/exasol-driver-go/issues/37

**Comment by pj-spoelders** [comment]
discussed with chipi, for this we'd need to replace gorilla websockets with our own exasol-driver-go which now supports this out of the box

**Comment by redcatbear** [comment]
Shelved, because not in roadmap focus.
