### ISSUE TITLE
Automate release to GitHub

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-rest-api#44]
Automate the release process for GitHub

**Comment by pj-spoelders** [comment]
There currently is a workflow made by Nastya that uploads the generated build artifacts to the release. 
(It prompts the user for the upload_url of the release, which we have to make manually first),
It can be included/adapted.

**Comment by pj-spoelders** [comment]
After having a closer look this workflow was intended to be used by/with release-droid.

**Comment by pj-spoelders** [comment]
TBD

**Comment by pj-spoelders** [comment]
This seems to work as intended right now. Succesfully made a release last week. Closing this ticket. Thanks @kaklakariada & others who worked on this.
